name = "mega-s4-vrc-cdn"
type = "module"

workers_dev = false
compatibility_date = "2025-03-05"
main= "index.js"

[vars]
AWS_DEFAULT_REGION = "g"
AWS_S3_BUCKET = "vrc-cdn"
ALLOW_LIST_BUCKET = "false"

[observability.logs]
enabled = true