name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 3 * * *' # every day at 03:00 UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch (where workflow lives)
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0

      - name: Set up Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch main branch
        run: git fetch origin main:main

      - name: Add upstream remote
        run: git remote add upstream https://github.com/meganz/s4-cloudflare.git

      - name: Fetch upstream
        run: git fetch upstream

      - name: Checkout main branch
        run: git checkout main

      - name: Try rebase onto upstream/main
        id: rebase
        continue-on-error: true
        run: |
          git rebase upstream/main

      - name: Force reset main branch if rebase failed
        if: steps.rebase.outcome == 'failure'
        run: |
          git reset --hard upstream/main

      - name: Remove all workflow files from main branch
        run: rm -rf .github/workflows/*

      - name: Commit workflow file removals (if any)
        run: |
          git add .github/workflows/* || true
          git commit -m "Remove workflow files from main branch" || true

      - name: Push changes to main branch
        run: git push origin main --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# Note: This workflow should only exist in the master branch. It will delete all workflow files from main after syncing.
#       If rebase fails, it will force reset main to upstream/main and re-delete workflow files.
#       Do not add this workflow to the main branch.
